############# Vietnamese navigation ##############

# main menu
[[main]]
name = "Trang chủ"
url = "/"
weight = 1

[[main]]
name = "Giới thiệu"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3




# footer menu
[[footer]]
name = "Giới thiệu"
url = "/about"
weight = 1

[[footer]]
name = "Thành phần"
url = "/elements"
weight = 2

[[footer]]
name = "Chính sách bảo mật"
url = "/privacy-policy"
weight = 3